#!/usr/bin/env node
/**
 * Cinescenes — Movie Import Script
 *
 * Reads ~/hitster-movies-candidates.md and generates:
 *   scripts/output/movies_import.sql  — all movies, active = false
 *
 * Usage:
 *   node scripts/import-movies.js
 *
 * Then run movies_import.sql in your Supabase SQL editor.
 * After the Phase 2 scanning pipeline sets youtube_id / safe_start /
 * safe_end, it will flip active = true automatically.
 */

const fs = require('fs');
const path = require('path');

const INPUT_FILE = path.join(__dirname, '../../hitster-movies-candidates.md');
const OUTPUT_DIR = path.join(__dirname, 'output');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'movies_import.sql');

function escape(str) {
  return str.replace(/'/g, "''");
}

function parseMovies(content) {
  const movies = [];
  let currentYear = null;
  let inMainList = false;

  const lines = content.split('\n');

  for (const line of lines) {
    // Detect year header: ## 1976
    const yearMatch = line.match(/^## (\d{4})/);
    if (yearMatch) {
      currentYear = parseInt(yearMatch[1], 10);
      inMainList = false;
      continue;
    }

    // Start of main list
    if (line.trim() === '**Main List:**') {
      inMainList = true;
      continue;
    }

    // End of main list (backlog or empty line after numbered entries)
    if (line.startsWith('**Backlog:**') || line.startsWith('---')) {
      inMainList = false;
      continue;
    }

    if (!inMainList || !currentYear) continue;

    // Match numbered entries:  1. Title | Director | Language | Tags
    const entryMatch = line.match(/^\d+\.\s+(.+)/);
    if (!entryMatch) continue;

    const parts = entryMatch[1].split('|').map((p) => p.trim());
    if (parts.length < 2) continue;

    const title = parts[0].replace(/\s*(REMOVE|REPLACE|KEEP)\s*/gi, '').trim();
    const director = parts[1].trim();

    // Skip explicit REMOVE entries
    if (line.includes('REMOVE')) continue;

    if (title && director && currentYear) {
      movies.push({ title, director, year: currentYear });
    }
  }

  return movies;
}

function generateSQL(movies) {
  const header = `-- ============================================================
-- Cinescenes — Full Movie Import (${movies.length} movies)
-- Generated by scripts/import-movies.js on ${new Date().toISOString()}
--
-- All movies start as active = false.
-- The Phase 2 scanning pipeline will set youtube_id, safe_start,
-- safe_end, and flip active = true when a clean window is found.
-- Movies that fail scanning will be set flagged = true.
-- ============================================================

insert into movies (title, year, director, active) values`;

  const values = movies
    .map(
      ({ title, director, year }) =>
        `  ('${escape(title)}', ${year}, '${escape(director)}', false)`
    )
    .join(',\n');

  return `${header}\n${values}\non conflict do nothing;\n`;
}

// ── Main ─────────────────────────────────────────────────────────────────────

if (!fs.existsSync(INPUT_FILE)) {
  console.error(`Input file not found: ${INPUT_FILE}`);
  console.error('Expected ~/hitster-movies-candidates.md to exist.');
  process.exit(1);
}

if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

const content = fs.readFileSync(INPUT_FILE, 'utf-8');
const movies = parseMovies(content);

if (movies.length === 0) {
  console.error('No movies parsed. Check the input file format.');
  process.exit(1);
}

const sql = generateSQL(movies);
fs.writeFileSync(OUTPUT_FILE, sql, 'utf-8');

console.log(`Parsed ${movies.length} movies.`);
console.log(`SQL written to: ${OUTPUT_FILE}`);
console.log('');
console.log('Next steps:');
console.log('  1. Run supabase/schema.sql in your Supabase SQL editor');
console.log('  2. Run supabase/seed_test_movies.sql (15 active test movies)');
console.log('  3. Run scripts/output/movies_import.sql to load all candidates');
console.log('  4. Run Phase 2 scanning pipeline to activate remaining movies');
