-- ============================================================
-- Cinescenes — Movies 2000-2017 (191 entries)
-- Generated 2026-03-13T07:28:37.618Z
--
-- Uses WHERE NOT EXISTS to skip movies already in the DB.
-- All new movies start as active = false.
-- Run the scan pipeline to activate them.
-- ============================================================

INSERT INTO movies (title, year, director, active)
SELECT v.title, v.year, v.director, v.active
FROM (VALUES
  ('Memento', 2000, 'Christopher Nolan', false),
  ('Gladiator', 2000, 'Ridley Scott', false),
  ('Cast Away', 2000, 'Robert Zemeckis', false),
  ('Amores Perros', 2000, 'Alejandro González Iñárritu', false),
  ('Dancer in the Dark', 2000, 'Lars von Trier', false),
  ('Requiem for a Dream', 2000, 'Darren Aronofsky', false),
  ('Billy Elliot', 2000, 'Stephen Daldry', false),
  ('Almost Famous', 2000, 'Cameron Crowe', false),
  ('Crouching Tiger, Hidden Dragon (臥虎藏龍)', 2000, 'Ang Lee', false),
  ('In the Mood for Love (花樣年華)', 2000, 'Wong Kar-wai', false),
  ('Harry Potter and the Philosopher''s Stone', 2001, 'Chris Columbus', false),
  ('The Lord of the Rings: The Fellowship of the Ring', 2001, 'Peter Jackson', false),
  ('Y Tu Mamá También', 2001, 'Alfonso Cuarón', false),
  ('Monsters, Inc.', 2001, 'Pete Docter', false),
  ('A Beautiful Mind', 2001, 'Ron Howard', false),
  ('Moulin Rouge!', 2001, 'Baz Luhrmann', false),
  ('Ocean''s Eleven', 2001, 'Steven Soderbergh', false),
  ('Mulholland Drive', 2001, 'David Lynch', false),
  ('Amélie (Le Fabuleux Destin d''Amélie Poulain)', 2001, 'Jean-Pierre Jeunet', false),
  ('No Man''s Land (Ničija zemlja)', 2001, 'Danis Tanović', false),
  ('Spirited Away', 2001, 'Hayao Miyazaki', false),
  ('Spider-Man', 2002, 'Sam Raimi', false),
  ('Gangs of New York', 2002, 'Martin Scorsese', false),
  ('City of God (Cidade de Deus)', 2002, 'Fernando Meirelles', false),
  ('My Big Fat Greek Wedding', 2002, 'Joel Zwick', false),
  ('The Quiet American', 2002, 'Phillip Noyce', false),
  ('Chicago', 2002, 'Rob Marshall', false),
  ('Catch Me If You Can', 2002, 'Steven Spielberg', false),
  ('Minority Report', 2002, 'Steven Spielberg', false),
  ('The Ring', 2002, 'Gore Verbinski', false),
  ('Hero (英雄)', 2002, 'Zhang Yimou', false),
  ('The Lord of the Rings: The Return of the King', 2003, 'Peter Jackson', false),
  ('Finding Nemo', 2003, 'Andrew Stanton', false),
  ('Pirates of the Caribbean: The Curse of the Black Pearl', 2003, 'Gore Verbinski', false),
  ('Good Bye, Lenin!', 2003, 'Wolfgang Becker', false),
  ('Bruce Almighty', 2003, 'Tom Shadyac', false),
  ('Mystic River', 2003, 'Clint Eastwood', false),
  ('Lost in Translation', 2003, 'Sofia Coppola', false),
  ('Master and Commander', 2003, 'Peter Weir', false),
  ('Oldboy (올드보이)', 2003, 'Park Chan-wook', false),
  ('The Barbarian Invasions (Les Invasions barbares)', 2003, 'Denys Arcand', false),
  ('Kill Bill', 2003, 'Quentin Tarantino', false),
  ('Shrek 2', 2004, 'Andrew Adamson', false),
  ('The Notebook', 2004, 'Nick Cassavetes', false),
  ('The Passion of the Christ', 2004, 'Mel Gibson', false),
  ('Sideways', 2004, 'Alexander Payne', false),
  ('The Incredibles', 2004, 'Brad Bird', false),
  ('The Machinist', 2004, 'Brad Anderson', false),
  ('Eternal Sunshine of the Spotless Mind', 2004, 'Michel Gondry', false),
  ('Million Dollar Baby', 2004, 'Clint Eastwood', false),
  ('The Sea Inside (Mar adentro)', 2004, 'Alejandro Amenábar', false),
  ('2046', 2004, 'Wong Kar-wai', false),
  ('Memoirs of a Geisha', 2005, 'Rob Marshall', false),
  ('Pride & Prejudice', 2005, 'Joe Wright', false),
  ('War of the Worlds', 2005, 'Steven Spielberg', false),
  ('Batman Begins', 2005, 'Christopher Nolan', false),
  ('King Kong', 2005, 'Peter Jackson', false),
  ('Crash', 2005, 'Paul Haggis', false),
  ('Brokeback Mountain', 2005, 'Ang Lee', false),
  ('Walk the Line', 2005, 'James Mangold', false),
  ('Caché (Hidden)', 2005, 'Michael Haneke', false),
  ('Tsotsi', 2005, 'Gavin Hood', false),
  ('Babel', 2006, 'Alejandro González Iñárritu', false),
  ('The Pursuit of Happiness', 2006, 'Gabriele Muccino', false),
  ('Night at the Museum', 2006, 'Shawn Levy', false),
  ('The Departed', 2006, 'Martin Scorsese', false),
  ('Little Miss Sunshine', 2006, 'Dayton & Faris', false),
  ('Borat', 2006, 'Larry Charles', false),
  ('Casino Royale', 2006, 'Martin Campbell', false),
  ('Children of Men', 2006, 'Alfonso Cuarón', false),
  ('Pan''s Labyrinth (El laberinto del fauno)', 2006, 'Guillermo del Toro', false),
  ('The Lives of Others (Das Leben der Anderen)', 2006, 'Florian H. von Donnersmarck', false),
  ('Michael Clayton', 2007, 'Tony Gilroy', false),
  ('Transformers', 2007, 'Michael Bay', false),
  ('No Country for Old Men', 2007, 'Coen Brothers', false),
  ('There Will Be Blood', 2007, 'Paul Thomas Anderson', false),
  ('Juno', 2007, 'Jason Reitman', false),
  ('Zodiac', 2007, 'David Fincher', false),
  ('Atonement', 2007, 'Joe Wright', false),
  ('Into the Wild', 2007, 'Sean Penn', false),
  ('Persepolis', 2007, 'Paronnaud & Satrapi', false),
  ('Sweeney Todd: The Demon Barber of Fleet Street', 2007, 'Tim Burton', false),
  ('Paranormal Activity', 2007, 'Oren Peli', false),
  ('The Dark Knight', 2008, 'Christopher Nolan', false),
  ('Iron Man', 2008, 'Jon Favreau', false),
  ('The Wrestler', 2008, 'Darren Aronofsky', false),
  ('Kung Fu Panda', 2008, 'Osborne & Stevenson', false),
  ('WALL-E', 2008, 'Andrew Stanton', false),
  ('Slumdog Millionaire', 2008, 'Danny Boyle', false),
  ('The Hurt Locker', 2008, 'Kathryn Bigelow', false),
  ('Gran Torino', 2008, 'Clint Eastwood', false),
  ('The Class (Entre les murs)', 2008, 'Laurent Cantet', false),
  ('Die Welle', 2008, 'Dennis Gansel', false),
  ('Avatar', 2009, 'James Cameron', false),
  ('The Blind Side', 2009, 'John Lee Hancock', false),
  ('(500) Days of Summer', 2009, 'Marc Webb', false),
  ('Up', 2009, 'Pete Docter', false),
  ('The Hangover', 2009, 'Todd Phillips', false),
  ('The Hurt Locker', 2009, 'Kathryn Bigelow', false),
  ('Inglourious Basterds', 2009, 'Quentin Tarantino', false),
  ('A Serious Man', 2009, 'Coen Brothers', false),
  ('The White Ribbon (Das weiße Band)', 2009, 'Michael Haneke', false),
  ('A Prophet (Un prophète)', 2009, 'Jacques Audiard', false),
  ('Law Abiding Citizen', 2009, 'F. Gary Gray', false),
  ('Los abrazos rotos', 2009, 'Pedro Almodovar', false),
  ('Toy Story 3', 2010, 'Lee Unkrich', false),
  ('Alice in Wonderland', 2010, 'Tim Burton', false),
  ('The Fighter', 2010, 'David O. Russell', false),
  ('Inception', 2010, 'Christopher Nolan', false),
  ('Despicable Me', 2010, 'Coffin & Renaud', false),
  ('The Social Network', 2010, 'David Fincher', false),
  ('The King''s Speech', 2010, 'Tom Hooper', false),
  ('Black Swan', 2010, 'Darren Aronofsky', false),
  ('Of Gods and Men (Des hommes et des dieux)', 2010, 'Xavier Beauvois', false),
  ('Uncle Boonmee Who Can Recall His Past Lives', 2010, 'Apichatpong Weerasethakul', false),
  ('The Ghost Writer', 2010, 'Roman Polanski', false),
  ('Harry Potter and the Deathly Hallows Part 2', 2011, 'David Yates', false),
  ('War Horse', 2011, 'Steven Spielberg', false),
  ('Hugo', 2011, 'Martin Scorsese', false),
  ('Moneyball', 2011, 'Bennett Miller', false),
  ('The Artist', 2011, 'Michel Hazanavicius', false),
  ('The Tree of Life', 2011, 'Terrence Malick', false),
  ('Drive', 2011, 'Nicolas Winding Refn', false),
  ('Midnight in Paris', 2011, 'Woody Allen', false),
  ('A Separation (جدایی نادر از سیمین)', 2011, 'Asghar Farhadi', false),
  ('Incendies', 2011, 'Denis Villeneuve', false),
  ('The Intouchables', 2011, 'Olivier Nakache & Eric Toledano', false),
  ('Carnage', 2011, 'Roman Polanski', false),
  ('Les Misérables', 2012, 'Tom Hooper', false),
  ('The Dark Knight Rises', 2012, 'Christopher Nolan', false),
  ('The Hunger Games', 2012, 'Gary Ross', false),
  ('Skyfall', 2012, 'Sam Mendes', false),
  ('Django Unchained', 2012, 'Quentin Tarantino', false),
  ('Argo', 2012, 'Ben Affleck', false),
  ('Lincoln', 2012, 'Steven Spielberg', false),
  ('Zero Dark Thirty', 2012, 'Kathryn Bigelow', false),
  ('Amour', 2012, 'Michael Haneke', false),
  ('The Hunt (Jagten)', 2012, 'Thomas Vinterberg', false),
  ('The Master', 2012, 'Paul Thomas Anderson', false),
  ('Silver Linings Playbook', 2012, 'David O. Russel', false),
  ('The Great Gatsby', 2013, 'Baz Luhrmann', false),
  ('American Hustle', 2013, 'David O. Russell', false),
  ('Enemy', 2013, 'Denis Villeneuve', false),
  ('Gravity', 2013, 'Alfonso Cuarón', false),
  ('Before Midnight', 2013, 'Richard Linklater', false),
  ('12 Years a Slave', 2013, 'Steve McQueen', false),
  ('Her', 2013, 'Spike Jonze', false),
  ('The Wolf of Wall Street', 2013, 'Martin Scorsese', false),
  ('The Great Beauty (La grande bellezza)', 2013, 'Paolo Sorrentino', false),
  ('The Tale of Princess Kaguya', 2013, 'Isao Takahata', false),
  ('Guardians of the Galaxy', 2014, 'James Gunn', false),
  ('Gone Girl', 2014, 'David Fincher', false),
  ('The Grand Budapest Hotel', 2014, 'Wes Anderson', false),
  ('The Fault in Our Stars', 2014, 'Josh Boone', false),
  ('Interstellar', 2014, 'Christopher Nolan', false),
  ('Birdman', 2014, 'Alejandro González Iñárritu', false),
  ('Boyhood', 2014, 'Richard Linklater', false),
  ('Whiplash', 2014, 'Damien Chazelle', false),
  ('Leviathan (Левиафан)', 2014, 'Andrey Zvyagintsev', false),
  ('Winter Sleep (Kış Uykusu)', 2014, 'Nuri Bilge Ceylan', false),
  ('Spotlight', 2015, 'Tom McCarthy', false),
  ('Room', 2015, 'Lenny Abrahamson', false),
  ('Ex Machina', 2015, 'Alex Garland', false),
  ('Bridge of Spies', 2015, 'Steven Spielberg', false),
  ('Sicario', 2015, 'Denis Villeneuve', false),
  ('The Martian', 2015, 'Ridley Scott', false),
  ('Mad Max: Fury Road', 2015, 'George Miller', false),
  ('The Revenant', 2015, 'Alejandro González Iñárritu', false),
  ('Son of Saul (Saul fia)', 2015, 'László Nemes', false),
  ('The Assassin (聶隱娘)', 2015, 'Hou Hsiao-hsien', false),
  ('Manchester by the Sea', 2016, 'Kenneth Lonergan', false),
  ('Hacksaw Ridge', 2016, 'Mel Gibson', false),
  ('Hell or High Water', 2016, 'David Mackenzie', false),
  ('Nocturnal Animals', 2016, 'Tom Ford', false),
  ('The Lobster', 2016, 'Yorgos Lanthimos', false),
  ('La La Land', 2016, 'Damien Chazelle', false),
  ('Moonlight', 2016, 'Barry Jenkins', false),
  ('Arrival', 2016, 'Denis Villeneuve', false),
  ('Toni Erdmann', 2016, 'Maren Ade', false),
  ('The Handmaiden (아가씨)', 2016, 'Park Chan-wook', false),
  ('Star Wars: The Last Jedi', 2017, 'Rian Johnson', false),
  ('Beauty and the Beast', 2017, 'Bill Condon', false),
  ('Call Me By Your Name', 2017, 'Luca Guadagnino', false),
  ('Okja', 2017, 'Bong Joon Ho', false),
  ('Dunkirk', 2017, 'Christopher Nolan', false),
  ('Get Out', 2017, 'Jordan Peele', false),
  ('The Shape of Water', 2017, 'Guillermo del Toro', false),
  ('Lady Bird', 2017, 'Greta Gerwig', false),
  ('The Square', 2017, 'Ruben Östlund', false),
  ('Three Billboards Outside Ebbing, Missouri', 2017, 'Martin McDonagh', false),
  ('Phantom Thread', 2017, 'Paul Thomas Anderson', false)
) AS v(title, year, director, active)
WHERE NOT EXISTS (
  SELECT 1 FROM movies
  WHERE movies.title = v.title AND movies.year = v.year
);
